# -*- coding: utf-8 -*-
"""Satellite affection of gravity throught time

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LU9YuydllPWs7oSvIsz1Gec-5ZPj5KjJ
"""

import numpy as np
import matplotlib.pyplot as plt

# Constants
gravitational_constant = float(6.67430e-11)  # Gravitational constant (m^3 kg^-1 s^-2)
earth_mass = float(5.972e24) # Mass of Earth (kg)
earth_radius = float(6371000.0) # Radius of Earth (m)

# Function to calculate gravitational force
def gravitational_force(mass_satellite, altitude):#gravitational constant formula
    r = altitude + earth_radius  # Distance from satellite to Earth
    force = (gravitational_constant * earth_mass * mass_satellite) / (r**2)  # Gravitational force
    return force

# Simulation parameters or inputs of your choice
mass_satellite = int(input("mass of satellite (kg): "))  # Mass of the satellite (kg)
initial_altitude = int(input("altitude of satellite (meters): "))  # Initial altitude of the satellite (m)
time = int(input("total time frame (sec): "))  # Simulation time (seconds)
time_step = int(input("time loops(sec): "))  # Time step (seconds)

# Arrays to store simulation data
altitude_values = []#arrays for both altitude and force values
force_values = []

# Simulation loop
altitude = initial_altitude#set altitude to given altitude by user
for _ in range (int(time / time_step)):#how long should it loop
    force = gravitational_force(mass_satellite, altitude)#call the gravitational force formula
    altitude -= (force / mass_satellite) * time_step  # Update altitude
    altitude_values.append(altitude)#assigned new forces/altitudes to their array
    force_values.append(force)

# Plotting
plt.figure(figsize=(10, 6))#size of plot
plt.plot(np.arange(0, time, time_step), force_values, color='blue')#range and height of array
plt.title('Gravitational Force Acting on Satellite Over Time')
plt.xlabel('Time (s)')#labels of x and y axis
plt.ylabel('Gravitational Force (N)')
plt.grid(True)
plt.show()#output the plot if succesful